### ISSUE TITLE
Charpter solution-gui of Redis documentation

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/ansible-redis#1]
RD: solution-gui(zh/en) need upload pictures

**Comment by qiaofeng1227** [comment]
1. how to create a redis database
2. how to create user and password

**Comment by chendelin1982** [comment]
Redis have not user, only a simple AUTH functions;  
Redis have not more databases for one instance;

**Comment by chendelin1982** [comment]
Need to translate CN to EN start from the charpter **Redis remote connection**

**Comment by chendelin1982** [comment]
Done
